# Generated by Django 4.2.7 on 2025-07-16 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0002_kmlboundary_survey_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='kmlboundary',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='kmlboundary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kmlboundary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kmlfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='kmlfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='surveyrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='surveyrecord',
            name='kml_file',
        ),
        migrations.RemoveField(
            model_name='surveyrecord',
            name='title',
        ),
        migrations.RemoveField(
            model_name='surveyrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kmlboundary',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='kmlboundary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlboundary',
            name='kitta_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kmlboundary',
            name='perimeter_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='kmlboundary',
            name='polygon_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/kml/'),
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='total_features',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='data_source',
            field=models.CharField(choices=[('CSV', 'CSV'), ('KML', 'KML'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='has_boundary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='kitta_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='land_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveyrecord',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kmlfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
