# Generated by Django 4.2.7 on 2025-07-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrecord',
            name='upload_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_records', to='surveys.uploadhistory'),
        ),
    ]
