# Generated by Django 4.2.7 on 2025-07-23 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0007_surveyrecord_upload_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('ACTION', 'Action'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
