# Generated by Django 4.2.7 on 2025-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_fileattachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmlfile',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='surveyrecord',
            name='data_source',
            field=models.CharField(choices=[('CSV', 'CSV'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.DeleteModel(
            name='KMLBoundary',
        ),
        migrations.DeleteModel(
            name='KMLFile',
        ),
    ]
