# Generated by Django 5.2.4 on 2025-07-20 05:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitta_number', models.CharField(help_text='Unique identifier for the land parcel', max_length=50, unique=True)),
                ('owner_name', models.CharField(help_text='Name of the land owner', max_length=200)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area of the land parcel in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('coordinates', models.TextField(help_text='Geographic coordinates in KML format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Parcel',
                'verbose_name_plural': 'Land Parcels',
                'ordering': ['-created_at'],
            },
        ),
    ]
